# set language
language: node_js

# set version of node_js to build against
node_js:
  - "4"

# set version of Firefox to use for add-on testing
addons:
  firefox: "47.0"

# run Firefox in headless mode
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# install JPM for building add-on
before_script:
  - npm install jpm -g

# run tests
script:
  - npm run jpm-travis
